### ISSUE TITLE
 Unexpected module 'Ng2FilterPipeModule' declared by the module 'AppModule'

### ISSUE THREAD

**Issue by aashirjaved** [VadimDez/ng2-filter-pipe#19] opened 2017-01-18 03:50 UTC
While including the module in App module generate this error on bootstrapping the application:

````Error: Unexpected module 'Ng2FilterPipeModule' declared by the module 'AppModule'
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:90821:27) [<root>]
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6643:16) [<root>]
    at http://localhost:4200/vendor.bundle.js:20597:40 [<root>]
    at Array.forEach (native) [<root>]
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:20579:54) [<root>]
    at JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:60779:64) [<root>]
    at JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:60739:52) [<root>]
    at JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:60705:21) [<root>]
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/vendor.bundle.js:44409:25) [<root>]
    at PlatformRef_.bootstrapModule (http://localhost:4200/vendor.bundle.js:44384:21) [<root>]
    at Object.630 (http://localhost:4200/main.bundle.js:595:124) [<root>]
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]
    at Object.1098 (http://localhost:4200/main.bundle.js:119:18) [<root>]
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30) [<root>]````

**Comment by VadimDez** [comment] 2017-01-18 11:48
Can't reproduce. Check the documentation maybe you missed something. Otherwise show how you import `Ng2FilterPipeModule`

**Comment by VadimDez** [comment] 2017-04-21 18:45
Closing. Not enough information.

**Closed by VadimDez** 2017-04-21 18:45 UTC
